# -*- coding: utf-8 -*-
"""Plant_Disease_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/mohsinnaweed/Plant-Disease-Detection-using-VGG16/blob/main/Plant_Disease_Detection.ipynb
"""

import os
import torch
import kagglehub
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, random_split

import torch.nn as nn
import torch.optim as optim

from sklearn.metrics import classification_report, confusion_matrix

path = kagglehub.dataset_download(
    "vipoooool/new-plant-diseases-dataset"
)

print("Dataset downloaded at:", path)

for root, dirs, files in os.walk(path):
    print(root)

data_dir = os.path.join(
    path,
    "New Plant Diseases Dataset(Augmented)",
    "New Plant Diseases Dataset(Augmented)",
    "train"
)

print(data_dir)

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

dataset = datasets.ImageFolder(
    root=data_dir,
    transform=transform
)

print("Total Classes:", len(dataset.classes))
print(dataset.classes[:10])
print("Total Images:", len(dataset))

from collections import Counter

labels = [label for _, label in dataset.samples]

class_count = Counter(labels)

plt.figure(figsize=(15,5))

plt.bar(class_count.keys(), class_count.values())

plt.title("Class Distribution")
plt.xlabel("Class Index")
plt.ylabel("Number of Images")

plt.show()

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size

train_dataset, test_dataset = random_split(
    dataset,
    [train_size, test_size]
)

print("Train Images:", len(train_dataset))
print("Test Images:", len(test_dataset))

train_loader = DataLoader(
    train_dataset,
    batch_size=16,
    shuffle=True,
    num_workers=2
)

test_loader = DataLoader(
    test_dataset,
    batch_size=16,
    shuffle=False,
    num_workers=2
)

model = models.vgg16(pretrained=True)

for param in model.features.parameters():
    param.requires_grad = False

model.classifier[6] = nn.Linear(
    4096,
    len(dataset.classes)
)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = model.to(device)

print(device)

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.0001
)

epochs = 5

best_accuracy = 0

train_losses = []
val_accuracies = []

for epoch in range(epochs):

    # TRAINING
    model.train()

    running_loss = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    epoch_loss = running_loss / len(train_loader)

    train_losses.append(epoch_loss)

    # VALIDATION
    model.eval()

    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in test_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)

            correct += (predicted == labels).sum().item()

    accuracy = 100 * correct / total

    val_accuracies.append(accuracy)

    # Save Best Model
    if accuracy > best_accuracy:

        best_accuracy = accuracy

        torch.save(
            model.state_dict(),
            "best_plant_model.pth"
        )

    print(f"Epoch [{epoch+1}/{epochs}]")
    print(f"Loss: {epoch_loss:.4f}")
    print(f"Accuracy: {accuracy:.2f}%")
    print("-"*40)

plt.figure(figsize=(10,5))

plt.plot(train_losses, label="Training Loss")
plt.plot(val_accuracies, label="Validation Accuracy")

plt.xlabel("Epoch")
plt.title("Training Progress")

plt.legend()

plt.show()

model.eval()

y_true = []
y_pred = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        y_true.extend(labels.numpy())

        y_pred.extend(predicted.cpu().numpy())

print(classification_report(
    y_true,
    y_pred,
    target_names=dataset.classes
))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(15,12))

sns.heatmap(
    cm,
    cmap="Blues"
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

from PIL import Image

def predict_image(image_path):

    model.eval()

    image = Image.open(image_path).convert("RGB")

    transform = transforms.Compose([
        transforms.Resize((224,224)),
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5])
    ])

    image = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():

        output = model(image)

        _, predicted = torch.max(output, 1)

    class_name = dataset.classes[predicted.item()]

    return class_name

from PIL import Image
import numpy as np

# Create a dummy image file for demonstration if it doesn't exist
image_path = "test_leaf.jpg"

if not os.path.exists(image_path):
    dummy_image = Image.fromarray(np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8))
    dummy_image.save(image_path)
    print(f"Created a dummy image at: {image_path}")

prediction = predict_image(image_path)

print("Prediction:", prediction)

def show_prediction(image_path):

    prediction = predict_image(image_path)

    img = Image.open(image_path)

    plt.figure(figsize=(6,6))

    plt.imshow(img)

    plt.title(f"Prediction: {prediction}")

    plt.axis("off")

    plt.show()

show_prediction("test_leaf.jpg")